name: Send event type to the repository dispatch

on:
  pull_request:
    types: [closed]

jobs:
  send-dispatch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Send Dispatch
      run: |
        curl -L -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/lucasgianine/automatic-dependency-update/dispatches \
        -d '{"event_type":"trigger"}'
