name: Send event type to the repository dispatch

on:
  pull_request:
    types: [closed]

jobs:
  send-dispatch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Send Dispatch
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
        https://api.github.com/repos/lucasgianine/automatic-dependency-update/dispatches \
        -d '{"event_type":"trigger"}'

  delete-branch:
    needs: send-dispatch
    # Após o PR ser mergeado, ele verificará se o dispatch funcionou, se sim, irá deletar a branch automaticamente
    if: success() && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          curl -L \
          -X DELETE \
          -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/git/refs/${{ github.head_ref }}
